baseURL = 'https://4rkal.eu.org/'
languageCode = 'en-us'
title = '4rkal'
theme = "PaperModX"
languageName = "English"
paginate = 100
enableRobotsTXT = true
defaultTheme = "dark"
[params.header]
desktopMode=  "fixed"
mobileMode = "auto"
[outputs]
home = ["HTML", "RSS", "JSON"]
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
  [[menu.main]]
  weight = 3
  identifier = "About"
  name = "About"
  url = "/about/"
  [[menu.main]]
  weight =4
  identifier = "Updates"
  name = "Updates"
  url = "/updates/"
 [[menu.main]]
 weight = 5
 identifier = "Donate"
 name = "Donate"
 url = "/donate/"
 
 [[menu.main]]
  weight = 6
  identifier = "Search"
  name = "Search"
  url = "/search/"
  title = "Search the site"



[params.homeInfoParams]
Title = "Welcome to 4rkal's blog 👋"
Content = "I'm **4rkal**. I generally post random stuff I stumble upon. Mostly about [<u>**linux**</u>](../../tags/linux), [<u>**privacy**</u>](../../tags/privacy), [<u>**crypto**</u>](../../tags/crypto), and [<u>**programming**</u>](../../tags/programming). I also love [<u>**selfhosting**</u>](../../tags/selfhosting) stuff."

[[params.socialIcons]]
name = "github"
url = "https://github.com/4rkal"

[[params.socialIcons]]
name = "twitter"
url = "https://x.com/4rkal_"

[[params.socialIcons]]
name = "email"
url = "mailto:4rkal@horsefucker.org"

[[params.socialIcons]]
name = "monero"
url = "/donate/"

[[params.socialIcons]]
name = "pgpkey"
url = ""

[[params.socialIcons]]
name= "rss"
url="/index.xml"

[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'

[markup.goldmark.renderer]
unsafe = true
[params.analytics.plausible]
dataDomain = "4rkal.eu.org"

[label]
text = "Home"
icon = "/favicon.ico"
iconHeight = 35
iconWidth = 35

[params]
description = "4rkal's blog"
images = ["4rkal.png"]
favicon = "4rkal.png"
TocOpen = true
TocSide = "left"
ShowReadingTime = true
ShowWordCount = true
ShowShareButtons = true
ShowCodeCopyButtons = true


[params.logo]
icon = "4rkal.png"
