baseURL = 'http://example.org/'
languageCode = 'en-us'
title = '4rkal'
theme = 'LoveIt'
languageName = "English"
paginate = 12
[author]
name = "4rkal"
email = "4rkal@proton.me"
[params.social]
Twitter = "4rkal_"
Github = "4rkal"
Reddit = "4rkal"
RSS = true
[params]
defaultTheme = "dark"
images = ["https://miro.medium.com/fit/c/96/96/1*GdbqNZk6c1ZxofwoXxehGA.jpeg"]
description = "4rkal's personal blog"
[params.header]
desktopMode=  "fixed"
mobileMode = "auto"
  [params.header.title]
  name = "4rkal"
  logo = "https://miro.medium.com/fit/c/96/96/1*GdbqNZk6c1ZxofwoXxehGA.jpeg"
[outputs]
home = ["HTML", "RSS", "JSON"]
[params.search]
  enable = true
  # type of search engine ["lunr", "algolia"]
  type = "lunr"
  # max index length of the chunked content
  contentLength = 4000
  # placeholder of the search bar
  placeholder = ""
  # LoveIt NEW | 0.2.1 max number of results length
  maxResultLength = 10
  # LoveIt NEW | 0.2.3 snippet length of the result
  snippetLength = 30
  # LoveIt NEW | 0.2.1 HTML tag name of the highlight part in results
  highlightTag = "em"
  # LoveIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
  absoluteURL = false
  [params.search.algolia]
    index = ""
    appID = ""
    searchKey = ""
 [params.seo]
    # image URL
    image = "https://miro.medium.com/fit/c/96/96/1*GdbqNZk6c1ZxofwoXxehGA.jpeg"
    # thumbnail URL
    thumbnailUrl = ""
   [params.page.share]
      enable = true
      Twitter = true
      Facebook = false 
      Linkedin = false 
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = true
      Reddit = true 
      VK = false
      Buffer = false
      Xing = false
      Line = false 
      Instapaper = false
      Pocket = false
      Flipboard = false
      Weibo = false 
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false

[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
  [[menu.main]]
  weight = 4
  identifier = "medium"
  name = "Medium"
  url = "https://4rkal.medium.com"
  [[menu.main]]
  weight = 3
  identifier = "About"
  name = "About"
  url = "/about/"
[params.home]
rss = 10
  [params.home.profile]
  enabled = true
  subtitle = "Programmer, crypto enthusiast."
  avatarURL = "https://miro.medium.com/fit/c/96/96/1*GdbqNZk6c1ZxofwoXxehGA.jpeg"
[params.page.toc]
  enabled=true
  keepStatic = false 
  auto=true 
